### ISSUE TITLE
Throwing exception with Shared Parameters in Test Case

### ISSUE THREAD

**Issue by mparsons007** [l3oferreira/MSTest.AzureDevOps#2]
I'm able to reference parameters specified in Test Cases directly (like the examples in the ReadMe), but when I tried to reference parameters from a Share Parameter set, I received the error below.  

And thanks for putting this package together!  It's been very helpful.

Result StackTrace:	
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at System.Data.DataSet.ReadXml(XmlReader reader, Boolean denyResolving)
   at System.Data.DataSet.ReadXml(TextReader reader)
   at MSTest.AzureDevOps.Attributes.AzureDevOpsDataSourceAttribute.GetData(MethodInfo methodInfo)
Result Message:	Data at the root level is invalid. Line 1, position 1.

**Comment by algorithminflux** [comment]
Also having this issue. I pulled in the DLL from your changes, @mparsons007, and it works like a charm.

Hoping the [PR for this](https://github.com/l3oferreira/MSTest.AzureDevOps/pull/3) will get merged sometime soon! 

Thanks again @l3oferreira for this NuGet package, very convenient. Cheers!

**Comment by eetawil** [comment]
@algorithminflux Hi, found two bugs in you PR. 

1. You assume that all shared parameters have values in them
`var myVal = dataRow.Kvp.First(x => x.Key  == column);` line 139 of AzureDevOpsDataSourceAttribute

2. If someone mixes both shared parameters and regular parameters in a Test case it also fails at the same line.

I will fix them , ill see after how to add it to github
